CREATE TABLE MY_ORDER (
    ORDER_ID INT PRIMARY KEY NOT NULL,
    SALE VARCHAR(1),
    TOTAL DOUBLE
);

CREATE TABLE PRODUCT (
    PRODUCT_ID INT PRIMARY KEY NOT NULL,
    ORDER_ID INT NOT NULL,
    NAME VARCHAR(50),
    QUANTITY INT,
    PRICE DOUBLE,
    FOREIGN KEY(ORDER_ID) REFERENCES MY_ORDER
);