CREATE TABLE MY_ORDER (
    ORDER_ID INT PRIMARY KEY NOT NULL,
    TOTAL DOUBLE
);

CREATE TABLE PRODUCT (
    PRODUCT_ID INT PRIMARY KEY NOT NULL,
    ORDER_ID, INT NOT NULL,
    NAME VARCHAR(50),
    QUANTITY INT,
    PRICE DOUBLE,
    FOREIGN KEY(ORDER_ID) REFERENCES MY_ORDER
);

CREATE TABLE ORDERED_PRODUCT {
    ORDER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT,
    FOREIGN KEY(ORDER_ID) REFERENCES MY_ORDER
}